name: Using Secret Token to Build JAVA

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  Using-Secret-Token:
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Check out code
        uses: actions/checkout@v2

      - name: Using Secret Token to compile and run
        run: |
          if [ "${{ secrets.USER_NAME }}" == "student" ] && [ "${{ secrets.PASSWORD }}" == "student@123" ]; then
            javac Addition.java
            java Addition
          else
            echo "Invalid username or password"
            exit 1
          fi
